name: CI/CD → GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build e Deploy para GitHub Pages
    runs-on: ubuntu-latest

    steps:
      # 1. Faz checkout do repo
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2. (Opcional) Insira validadores ou linters, se quiser
      # - name: Rodar Linter
      #   run: echo "adicione seus comandos de lint aqui, se necessário"

      # 3. Inicializa o Pages Action
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      # 4. Copia todos os arquivos que serão publicados
      - name: Empacotar artefato (criar pasta public/)
        run: |
          mkdir -p public
          cp -R ./* public/

      # 5. Carrega o conteúdo de public/ para o Pages
      - name: Fazer upload do artefato para GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

      # 6. Finalmente, faz o deploy no GitHub Pages
      - name: Deploy para GitHub Pages
        uses: actions/deploy-pages@v1
